### PR TITLE
iTunes lookup API can return Array

### PR DESCRIPTION
**Pull request by bugcloud**
There are some cases we want to get result array via iTunes lookup API.

ex)
https://itunes.apple.com/lookup?amgArtistId=468749,5723&entity=album&limit=5

### CODE REVIEW

**Comment by rickpern** [comment]
:+1:

**Comment by rlivsey** [comment]
Sorry for the delay in merging this

**Comment by rlivsey** [comment]
@bugcloud thanks for the commit, I've added you as a collaborator so you can push changes directly now

**Comment by bugcloud** [comment]
@rlivsey Thanks!

**Pull request merged**
